### ISSUE TITLE
第Z条冒頭の文に不要なスペースがある

### ISSUE THREAD

**Issue by nikken7101** [kotarot/wca-regulations-translations#10]
第Z条冒頭の文
`
大会運営チームは大会運営を容易にするためのオプション規則を追加採用することができる。 オプション規則を大会に適用するには WCA 理事会の承認を得なければならない。
`
の
`できる。`と`オプション規則`の間の半角スペースは不要と思われます。

**Comment by kotarot** [comment]
生成されたページ上ではこの部分に半角スペースが入っていますが、マークダウンファイル上ではこの部分に改行が挿入されています。すなわち、第Z条冒頭の文がファイル上は2行にわたって記述されています。
原文も同様に2行で記述されていて、原文と対応させるためにこのようになっています。
見た目的にはこの改行を取り除きたいところですが、保留します。

**Comment by nikken7101** [comment]
改行のせいだったのですね。よく確認せずにすみません。修正しなくて良いと思います。
