### ISSUE TITLE
お問い合わせ先のリンクについて

### ISSUE THREAD

**Issue by Yoheicube** [kotarot/wca-regulations-translations#12]
お問い合わせ
質問・ご指摘等は WCA 大会規則委員会へお問い合わせください。

翻訳お疲れ様です。
WCA大会規則委員会のリンクが切れているようです。
先ほど確認したら、Regulation原案もリンク切れになっているようでしたので投稿済みです。
変更があると思いますので、その際は日本語版も変更をお願いします。

**Comment by kotarot** [comment]
本当ですね。原文が変更され次第、日本語も追従したいと思います。
wca-documentsへの報告もしていただいてありがとうございます！

**Comment by kotarot** [comment]
原文が修正されました。日本語も同様に修正します。
https://github.com/cubing/wca-documents/commit/12a96ae7bcdc81c32f21fc6f4230d2f79dd63c63

**Comment by kotarot** [comment]
修正しました。
