### ISSUE TITLE
2u1) 日本語の表現について

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#13]
レギュレーション 2u1)
日本語が少しおかしいかと思います。

WCA 代理人の裁量により試技を辞退したもの（DNS）とみなされることができる。

→ みなすことができる or みなす場合がある 
とかですかね。

**Comment by kotarot** [comment]
この文は「競技者は」が主語なのでできるだけ「～される」という表現にしたいです。
確かに「できる」は日本語が変なので、

```
競技者は WCA 代理人の裁量により試技を辞退したもの（DNS）とみなされることがある。
```

ぐらいが自然になると思いました。

もしくは、受動態のまま訳さず、

```
競技者を WCA 代理人の裁量により試技を辞退したもの（DNS）とみなすことができる。
```

とすると自然だと思いました。

個人的には後半を推します。いずれにしてもどちらかに変更したいと思います。
ご指摘ありがとうございます。

**Comment by kotarot** [comment]
後半の表現にしてみました。

**Comment by roudai** [comment]
OKだと思います。
