### ISSUE TITLE
3j3) 「手触りのある」

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#14]
「手触りのある」というのは、少しおかしい気がします。

「手触りがある」「ざらつきのある（原文texturedの意味より http://eow.alc.co.jp/search?q=textured&ref=sa）」等

**Comment by kotarot** [comment]
textured はざらつきがあるというのに必ずしも限らないと考えますので「ざらつきのある」はちょっと限定的すぎる気がします。
「手触りがある」が無難と思いますので、修正します。

**Comment by kotarot** [comment]
これに連動して 3d1 の「手触りを持つ」を「手触りがある」に変更します。

**Comment by kotarot** [comment]
変更しました。

**Comment by roudai** [comment]
確認しました。OKです。
