### ISSUE TITLE
第C条：片手競技 内の訳

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#16]
第C条：片手競技 内で、
「ソルビング中」「ソルビ中」という訳があります。
（原文までは確認していませんが）「試技中」に統一したほうが良いかと思います。

**Comment by kotarot** [comment]
原文では "solve" と "attempt" を明確に区別しています。
（どう区別してるのかはよくわかりません笑 誰か教えてください）

JRCAのフォーラムに記載したように、solve はソルブ、attempt は試技と訳すように統一していますので、ここは「ソルブ中」に統一します。

**Comment by kotarot** [comment]
とりあえず修正しました。

**Comment by roudai** [comment]
了解しました。原文と対比が取れて訳されているのならそれで良いと思います。
ソルビング中とソルブ中があるのは違和感あったので、ソルブ中に統一でOKです。
