### ISSUE TITLE
板状の物体

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#17]
"thin object"を「板状の物体」と訳していますが、少し仰々しすぎると思います。
「板状のもの」でどうでしょう。

**Comment by kotarot** [comment]
いいですね。もはや「板」でもいいかもしれません。
けど紙とかも thin object ですからやっぱ「板状のもの」ですね。

**Comment by kotarot** [comment]
でも紙が「板状のもの」に含まれるか怪しい感じがしてきました。
素直に「厚さの薄いもの」？

**Comment by kotarot** [comment]
「厚みの薄い」、「厚みが薄い」、「厚みのない」

**Comment by kotarot** [comment]
「薄い」

**Comment by roudai** [comment]
直訳すると「薄いもの」ですが、ちょっと意味分からないですよね。
最初に単語がでてくるときだけ、「薄いもの（板や紙等）」と注釈入れるとか。

**Comment by roudai** [comment]
注釈じゃなくても、「薄い板や紙」でもいいかも

**Comment by kotarot** [comment]
「薄い板や紙」が一番的を得てると思いましたのでこれにします。

**Comment by roudai** [comment]
確認しました。OKです。
