### ISSUE TITLE
E2a、E2b1 「ゴー」「止め」

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#18]
A3b1、B2aで「READY?（準備はよろしいですか？）」と修正をしたのと同様に、
「GO（開始）」「STOP（止め）」と修正すべきかと思います。

**Comment by kotarot** [comment]
確かにその通りですね。直します。

**Comment by kotarot** [comment]
直しました。

**Comment by roudai** [comment]
「GO（ゴー）」に直してますが、そうします？
日本人でゴーなんて言う人いない気がしますが。

**Comment by kotarot** [comment]
「GO（開始）」の方がいいですね。単純に見落としてました。

**Comment by kotarot** [comment]
「止め」と対立させるなら「始め」でもいいですね。

**Comment by roudai** [comment]
止めの反対なら始めですね。それでいいと思います。

**Comment by kotarot** [comment]
「GO（始め）」にしました。

**Comment by roudai** [comment]
確認しました、OKです。
