### ISSUE TITLE
E3d watch

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#19]
原文が「watch」なので、訳は腕時計で正しい（置時計だとclock）と思うのですが、これは置時計は禁止だということでいいんですかね？
clockだとRubik's Clockとややこしいということでclockという単語を使っていないのなら、腕時計ではなく単に時計としたほうがいいかもしれません。

**Comment by kotarot** [comment]
原文の改訂のディスカッションに書いてあるかもしれないので確認してきます。

**Comment by nikken7101** [comment]
Clock可と書いてありますよ。
https://www.worldcubeassociation.org/posts/wca-regulations-july-2015
https://github.com/cubing/wca-documents/issues/217

**Comment by kotarot** [comment]
西さんありがとう！
「時計」でいいですね。

**Comment by kotarot** [comment]
「時計」にしました

**Comment by roudai** [comment]
確認しましたー、OKです。
