### ISSUE TITLE
A1a4+) についての質問

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#20]
A1a4+) [REMINDER] If a competitor has accidentally been permitted to exceed the time limit, the time limit must be enforced retroactively, and the judge, competitor, and WCA Delegate should be informed

A1a4+) [注意] 競技者が図らずも制限時間を越した場合、時間制限が遡って適用される。ジャッジ、競技者、WCA 代理人はそのことを知らされなければならない

について、どういうルールなのかイマイチ分からないんですが、これなんなんでしょう？
「図らずも制限時間を越した場合」とは。

**Comment by kotarot** [comment]
「図らずも」は "accidentally" の苦し紛れの日本語です。的確に表す日本語が思いつかなかったので悩みました。
要するに、競技者が故意ではなく (=accidentally) 制限時間を超過してしまった場合、...... ということです。

説明的に書くならば、

```
競技者が（競技者自身やジャッジの）故意的でない状況で制限時間を越した場合、時間制限が遡って適用される。
```

単に制限時間をオーバーしたという出来事ではなく、故意的ではないという条件を明示的に書く必要があります。
何かいい感じのアイデアがあれば教えてください。

**Comment by Yoheicube** [comment]
お疲れ様です。
いい日本語が浮かびませんが、このルールの意図としては、たとえば制限時間が2分として、ジャッジが2分を過ぎているのに競技を止めずに2分30秒で完成させた場合に、さかのぼって制限タイム2分が適用されてDNF扱いになるということです。
過去にこのルールがないときに、止めなかったのはジャッジの過失だというクレームが出て、そのまま認められた人と、厳格にジャッジが2分で競技を止めさせてDNFになった人がいて、不公平が出たことからこのルールが制定されました。

**Comment by roudai** [comment]
そのまま日本語にしても分からなそうですね。
あと、must beのニュアンスを入れないと理解しにくいと思います（時間を超えていても、制限時間は絶対適用しないといけない、的な意味で）

競技者が制限時間を超えて試技をしてしまった場合でも、制限時間は必ず適用される。

くらいでしょうか。

**Comment by roudai** [comment]
「故意的に」のニュアンスは「しまった」に入れてみた。
「遡って」とか「遡及的に」っていうのはわかりづらいんで無理に入れなくてもいいかと。

**Comment by kotarot** [comment]
ルールの解釈を説明していただきありがとうございます。
確かに「さかのぼって」は入れなくても意味は同じになると思います。

```
A1a4+) 競技者が制限時間を超えて試技をしてしまった場合でも、制限時間は必ず適用される。その後、ジャッジ、競技者、WCA 代理人はそのことを知らされることが望ましい
```

この文章を規則の方の条文 A1a4 に続けて読むと意味が通ると思います。
2文目は現在のままだとこのルールを知っていることが望ましいという風に解釈できるため、「その後」を2文目の文頭に入れました。

**Comment by nikken7101** [comment]
「遡って」は重要だと思います。私も後で案を出します。

**Comment by nikken7101** [comment]
accidentallyはpermittedの方にかかっているので、この部分訳出しないと変な気もします。

**Comment by nikken7101** [comment]
「競技者が故意ではなく制限時間を超過してしまった場合」というニュアンスではなく、
「ジャッジが故意でなく、制限時間の超過を認めてしまった場合」というニュアンスで訳すべきではないでしょうか

**Comment by nikken7101** [comment]
これでどうでしょうか。

# 修正案

`A1a4+) 誤って競技者の制限時間超過が認められてしまった場合も、制限時間は遡って適用されなければならない。また、ジャッジ、競技者、WCA 代理人はそのことを知らされることが望ましい。`

**Comment by kotarot** [comment]
OKだと思います。反対意見、改良意見がなければこれに変更しようと思います。

**Comment by roudai** [comment]
過不足なく、いいと思います。

**Comment by nikken7101** [comment]
書き忘れましたが、「遡って」を入れたほうがいいと思う理由は、「ジャッジが認めたのに"後から"DNFとかおかしいだろ！」という競技者のクレームがあった場合、「遡って」と明記されていることが説明に役立つと思うからです。ただ、「必ず適用される」だけだと、「でも後からなんてやっぱりおかしいだろ！」という人が出かねないと思います。

**Comment by kotarot** [comment]
変更しました。ついでに、3文目が「時間制限」になってたので「制限時間」に統一しました。

**Comment by nikken7101** [comment]
ありがとうございます。
