### ISSUE TITLE
2c1) 完全な登録

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#23]
「大会運営組織によって定められた完全な登録をしなければ」だと直訳で少し変な日本語なので、
「大会運営組織によって定められた登録を完全にしなければ」としてはどうでしょう。

**Comment by kotarot** [comment]
いいと思いますので修正しました。
追加で、この条文で organisation team の訳が他の箇所と不統一だったため、統一しました。

**Comment by roudai** [comment]
確認しました。OKです。
