### ISSUE TITLE
内容 文章見直し

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#27]
「条項の間に間がある場合があります」
という日本語がおかしいです。

「一部欠落がある場合があります。」
「歯抜けになっている場合があります。」

**Comment by kotarot** [comment]
`注釈：大会規則の条項の一部が削除された場合に改めて番号を振り直していないため、条項番号に抜けがある場合があります。`
にしました。

**Comment by roudai** [comment]
OKです。
