### ISSUE TITLE
2e1) の資格のある国の参照先が不明確

### ISSUE THREAD

**Issue by nikken7101** [kotarot/wca-regulations-translations#3]
# 修正箇所

2e1
# 修正案

`2e1) 資格のある国は英語版ウィキペディア記事「List of sovereign states」によって定義される（「UN member states and observer states」と「Other states」）。`
# 理由

現状の日本語版では

```
2e1) 資格のある国はウィキペディア記事「国の一覧」によって定義される（「国連加盟国とオブザーバー国」と「そのほかの国」）。
```

とありますが、原文では

```
2e1) The eligible countries are defined by the Wikipedia article "List of sovereign states" ("UN member states and observer states" and "Other states").
```

となっており、英語版Wikipediaが「資格のある国」参照先として適切なものだと思います。
`"List of sovereign states"`や`"UN member states and observer states" and "Other states"`を日本語にしてしまうと、参照先が不明瞭になるのではないでしょうか。そもそも日本語版ウィキペディアの「国の一覧」には、「オブザーバー国」や「そのほかの国」という表記はありません。
中国語版と韓国語版を確認しましたが、この部分は訳していませんでした。

**Comment by kotarot** [comment]
修正案に賛成します。私も参照先は原文の英語版ウィキペディア記事の方が適切だと思います。
英語版記事「List of sovereign states」と日本語版記事「国の一覧」の掲載国に相違は無いため、訳注として日本語版の参照を付加しておくのはどうでしょうか。

修正案です。

```
2e1) 資格のある国は英語版ウィキペディア記事「List of sovereign states」（「UN member states and observer states」と「Other states」）によって定義される（訳注：同内容の日本語版ウィキペディア記事「国の一覧」）。
```

**Comment by nikken7101** [comment]
訳注いいですね。 賛成です。

**Comment by kotarot** [comment]
参照先を英語版ウィキペディア記事にして訳注を加えました。
