### ISSUE TITLE
1e1a) ジャッジ

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#32]
もはやイチャモンに近いので無視してもいいですが、

1e1a) 常に全ての大会規則が遵守されているとジャッジが保証できるときに限り、WCA 代理人の裁量によりジャッジは複数の競技者を同時にジャッジすることができる。

最後の「ジャッジすることができる」のジャッジだけが、人をさす「ジャッジ」ではなく「審判する」という意味で使われており、紛らわしいかと思います。

「複数の競技者に同時につくことができる」
くらいでしょうか。

原文が"A judge may judge"だからすでにややこしいんだけど。

**Comment by kotarot** [comment]
イチャモンと言いつつ言いたいことはわかります。

この文章では、1つの文で3回も「ジャッジ」が出現するため、かなり冗長に感じられます。
（ちなみに、JRCAのスレッド内でも参照した日本語スタイルガイドでは「1 文内で同じ用語は重複して使いません。」と書かれています。）

この文の場合、(1) 前半部の主語がジャッジであること、(2) 「ジャッジする」とだけ書いてもその動作主はジャッジであることが自明である、ことから後半部の主語を省略しても良いと考え、

```
1e1a) 常に全ての大会規則が遵守されているとジャッジが保証できるときに限り、WCA 代理人の裁量により複数の競技者を同時にジャッジできる。
```

を提案しますが、いかがでしょうか。

**Comment by roudai** [comment]
その案では、やはり名詞の「ジャッジ」と動詞の「ジャッジする」が使われていて、最初に言っていた懸念が解決されていません。
（ちなみに動詞として「ジャッジ」を使っているのは全体を見てもこの一箇所だけです）

後半の主語が省略できるのはそのとおりだと思うので、

```
WCA 代理人の裁量により複数の競技者に同時にジャッジにつくことができる。
```

とするか、または「ジャッジに」も自明なので

```
WCA 代理人の裁量により複数の競技者に同時につくことができる。
```

としてはどうでしょう。

**Comment by kotarot** [comment]
ここは

```
WCA 代理人の裁量により複数の競技者に同時にジャッジにつくことができる。
```

にしようと思います。

<hr>

> （ちなみに動詞として「ジャッジ」を使っているのは全体を見てもこの一箇所だけです）

ちなみに、私がこの文で「ジャッジする」という動詞を使った理由は、規則とガイドライン中には「ジャッジする」という表現はありませんが、「ジャッジをする」と「ジャッジを行う」という表現が合計7か所あります。

「～をする」や「～を行う」は曖昧な日本語で、この場合、
- 「ジャッジする」という動詞の冗長表現
- 「ジャッジ（という役割を担当）する」の短縮表現

で捉えることができてしまいます。私は前者で解釈していたので、この文で「ジャッジする」と動詞表現を用いても紛らわしさは生じないと考えに至りました。
まあ、本大会規則とガイドラインではどっちで解釈しても本質的な意味は変わらないため、この問題はひとまずおいておきます。

**Comment by roudai** [comment]
まぁ細かい話なのであまり気にしないでください。
それで修正お願いします。

**Comment by kotarot** [comment]
OKです。
