### ISSUE TITLE
1c)  責任

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#33]
日本語スタイルガイドの「1 文内で同じ用語は重複して使いません。」に関連して、もうひとつ気になるところがあります。

> （原文）
> 1c) The WCA Delegate may delegate responsibilities to other members of the organisation team, 
> but is ultimately accountable for how these responsibilities are carried out.
> 
> （日本語訳）
> 1c) WCA 代理人は大会運営チームの他のメンバーに責任を委任してもよいが、最終的にはそれらの責任
> の任務遂行について責任を持つ。

「責任」という単語が出てきすぎて、特に後半の分がとてもわかりにくくなっています。
原文の「responsibilities」と「accountable」を両方「責任」と訳しているのが原因かと思います。

といいつつ、いい訳が思いつきません。

**Comment by kotarot** [comment]
`1c) WCA 代理人は大会運営チームの他のメンバーに責任を委任することができるが、それらの責任がどのように遂行されたか最終的な説明義務を持つ。`

とかどうでしょうか。任務には責任の意味が含まれるので意味が重なるので取り除きました。
accountable を複数の英和辞典で調べたら単に責任があるというよりは、説明できるみたいな意味だったためこうしました。

**Comment by roudai** [comment]
よくなりましたね。いいと思います。

**Comment by kotarot** [comment]
反映

**Comment by roudai** [comment]
OK
