### ISSUE TITLE
A1a2+) 丸括弧

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#34]
ジャッジは () を用いて
の括弧が半角なのは意図的に残していますか？
あとの(1:02.27)に合わせて半角にしているのかもしれませんが、
やはり見た目違和感あるので全角でもいいかもしれません。

**Comment by kotarot** [comment]
これ原文見たら文章で書いてあったので、日本語でも「......ジャッジは丸括弧を用いて......」って日本語で書くようにします（例を示してるからこれが原因で混乱することはないでしょう）。

それから、例を丸カッコではなく鍵カッコで示すことにします（原文はダブルクオーテーションで囲ってるのでむしろこっちの方が原文に近い訳です）。

`A1a2+) [追記] 制限時間が累積方式の場合、ジャッジは「DNF (1:02.27)」のように丸括弧を用いて DNF の横に元の記録も残す。`

括弧の中が半角英数字のみの場合、括弧が全角だと逆に見た目が悪くなる気がします。
今までは、閉じカッコが半角と全角が連続してたので変な見た目でしたが、これでそんな変じゃなくなる気がします。

**Comment by roudai** [comment]
半角英数字につく括弧は半角のほうがいいと思います。
めっちゃよくなりましたね。

**Comment by kotarot** [comment]
反映

**Comment by roudai** [comment]
OK
