### ISSUE TITLE
A3c3+) accidentallyの訳

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#35]
```
ジャッジが図らずもタイマーをリセットし忘れた場合、
```

「図らずも」というのは少し分かりにくいので、

```
ジャッジがタイマーをリセットし忘れてしまった場合、
```

としてもいいかもしれません。

同様に、

```
競技者が図らずもジャッジがリセットし忘れたタイマーで試技を開始しようとした場合
```

も変えたいですが、「ジャッジがリセットし忘れてしまったタイマー」というのもすこし冗長なので、あえてaccidentlyを訳さず、また主語（競技者）のあとが長すぎるので後にもってきて、

```
ジャッジがリセットし忘れたタイマーで競技者が試技を開始しようとした場合
```

でいい気がします。

全文にすると、

 A3c3+) [明示] ジャッジがタイマーをリセットし忘れてしまった場合、競技者はインスペクションタイムの前または途中にタイマーをリセットしてもよい。しかし、タイマーをリセットすることはジャッジの責務である（参照： 規則 A3b）。ジャッジがリセットし忘れたタイマーで競技者が試技を開始しようとした場合（すなわち、競技者 がインスペクションし、手をタイマーに適当な時間置き、タイマーが通常のようにスタートしたと思われる場合）、その試技は WCA 代理人の裁量により追加試技で置き換えられることが望ましい。

accidentallyの訳は難しいですね。

**Comment by kotarot** [comment]
原文を読み直して訳を再考してみました。

```
ジャッジが図らずもタイマーをリセットし忘れた場合、
```

↓

```
ジャッジが誤ってタイマーをリセットしそびれた場合、
```

原文に「忘れる」といったニュアンスの表現はありませんでしたので変えました。しかしaccidentallyを省いてしまうと、わざとリセットしない場合を排除しきれないためなるべく取り除かない方針でいきたいです。

```
競技者が図らずもジャッジがリセットし忘れたタイマーで試技を開始しようとした場合
```

↓

```
ジャッジがリセットしなかったタイマーで競技者が誤って試技を開始しようとした場合
```

**Comment by roudai** [comment]
しそびれた、というのはちょっと砕けすぎじゃないかなと思います。

```
ジャッジが誤ってタイマーをリセットしなかった場合、
```

でいいんじゃないかと。

後半の文、accidentallyは競技者にかかってたんですね。
こっちはそれでいいと思います。

**Comment by kotarot** [comment]
そうですね。それを採用します。

**Comment by kotarot** [comment]
反映

**Comment by roudai** [comment]
OK
