### ISSUE TITLE
第B条 スライスを回転

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#37]
```
B3c) 競技者は記憶段階の間、パズルのスライスを回転させてはならない。
```

```
B4b) 競技者は完全に目隠しを着用するまではパズルのスライスを回転させてはならない。
```

いいたいことは分かるんですが、スライスを回転ってなんとかなりませんかね。。。

**Comment by kotarot** [comment]
「パズルを回転させてはならない」に変更します。

これは、A3c1 の「パズルを回転させてはならない」に合わせる形になります（どちらも "must not apply moves" の訳です）。

**Comment by roudai** [comment]
「パズルを回転」だとパズル本体を回転させるのも含んでしまうのであえてスライスを、と入れてる気はするけど、
まぁ別にいいと思います。

**Comment by kotarot** [comment]
とりあえず「パズルを回転」。

全体にわたって、"turn", "move", "apply move" あたりの日本語をちゃんと考えて統一する必要がありますが、今回は時間がないのでやりません。

**Comment by roudai** [comment]
OKです。
