### ISSUE TITLE
B4c3) 

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#38]
`B4c3) If the judge and competitor agree beforehand, the competitor may choose to place the puzzle behind a suitable object (e.g. a music stand, the surface of the table) by himself during the blindfolded phase.`

`B4c3) 事前にジャッジと競技者の同意があれば、競技者は目隠し中にパズルを適切な物体（例：譜面台、机の天板）の向こう側にパズルを配置することを選択してもよい。`

「パズルを」が2回あるし、"by himself" が訳されていないし、全然ダメですね。

**Comment by roudai** [comment]
`B4c3) 事前にジャッジと競技者の同意があれば、競技者は目隠し段階の間、自分自身でパズルを隠すもの（例：譜面台、机の天板）を用いてもよい。`

**Comment by kotarot** [comment]
クリアになりましたね。それにします。

**Comment by kotarot** [comment]
一応報告。日本語訳には影響ありませんが、himself は gender-neutral に反するので themselves に変更したらどうかって原文の方に指摘しました。

**Comment by roudai** [comment]
それも気になってました。どうも。

**Comment by kotarot** [comment]
himself -> themself に修正されました（日本語関係ないけど）。
https://github.com/cubing/wca-documents/commit/afd6f34395bf0071692ae7672d933ec1ee2eb4dc

この条文の日本語訳はもう少し考えます。

**Comment by kotarot** [comment]
結局、

> B4c3) 事前にジャッジと競技者の同意があれば、競技者は目隠し段階の間、自分自身でパズルを隠すもの（例：譜面台、机の天板）を用いてもよい。

にしました。

**Comment by roudai** [comment]
OKです
