### ISSUE TITLE
B5a) スタックマット

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#39]
原文がStackmatになってますが、スタックマットタイマーのほうが正しい気がします。

**Comment by kotarot** [comment]
原文の方に指摘しましたので、変更され次第日本語も変更します。
とりあえず保留にします。

**Comment by kotarot** [comment]
原文が変更されました。
https://github.com/cubing/wca-documents/commit/d6e996a9214b7ded636f346212be48ff3dcd02c6

**Comment by roudai** [comment]
OK
