### ISSUE TITLE
B5a) B5b) When using

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#40]
`B5a) When using the Stackmat,`
`B5b) When using a stopwatch,`

と同じ表現なのに、

`B5a) スタックマット使用時`
`B5b) ストップウォッチ使用の場合`

としているので、どちらかに統一。

**Comment by roudai** [comment]
を使う場合、のほうがいいかも

**Comment by kotarot** [comment]
既存の表現として、A4dとB2eに「を使用する場合」があるので、それに合わせます。

**Comment by roudai** [comment]
OK
