### ISSUE TITLE
3d1, 3d1a, 3d1b の追加

### ISSUE THREAD

**Issue by kotarot** [kotarot/wca-regulations-translations#46]
3d1, 3d1a, 3d1b の追加
https://github.com/cubing/wca-documents/commit/06c7c0bcce109e18523806efd8ede6b79ff137f2

**Comment by kotarot** [comment]
3d1 の追加改訂
https://github.com/cubing/wca-documents/commit/5cb98a8f57405318b20adc7f1586245ddcc3517f

**Comment by kotarot** [comment]
...... この後何回か改訂を繰り返して ......

3d1 の最新版
https://github.com/cubing/wca-documents/commit/a9693fb7b10ffc1fc3838d0bec99172d10db5c20

**Comment by kotarot** [comment]
TODO: これを訳す

**Comment by kotarot** [comment]
原文新規追加箇所で誰も日本語をチェックしてないことに気づいたので issue をリオープンしました。
@roudai @nikken7101 時間があったらチェックしてください。

**Comment by roudai** [comment]
内容確認しました。特に問題ないと思います。

**Comment by kotarot** [comment]
どうもありがとうございます。

**Comment by nikken7101** [comment]
#54 の件以外はOKだと思います。
