### ISSUE TITLE
3d1b+ の追加

### ISSUE THREAD

**Issue by kotarot** [kotarot/wca-regulations-translations#47]
3d1b+ の追加
https://github.com/cubing/wca-documents/commit/41a493fc7667e3599759a7db5838f51192c31882

**Comment by kotarot** [comment]
3d1b+ の追加改訂
https://github.com/cubing/wca-documents/commit/9170441a06221dd75fa2eb522cd3c171f109d240

**Comment by kotarot** [comment]
原文新規追加箇所で誰も日本語をチェックしてないことに気づいたので issue をリオープンしました。
@roudai @nikken7101 時間があったらチェックしてください。

**Comment by roudai** [comment]
内容確認しました。特に問題ないと思います。

**Comment by kotarot** [comment]
どうもありがとうございます。

**Comment by nikken7101** [comment]
確認しました。OKだと思います。
