### ISSUE TITLE
9b) 「以下のとおり」を「以下の通り」に修正

### ISSUE THREAD

**Issue by nikken7101** [kotarot/wca-regulations-translations#5]
# 修正箇所

9b
# 修正案

`9b) WCA 公式パズル及び競技方式は以下のとおりである。`
# 修正理由

`以下のとおり`という表現は他にないが、`以下の通り`という表現は7箇所あるので、統一すべき

**Comment by kotarot** [comment]
統一すべきなのは明らかですので、統一しました。
