### ISSUE TITLE
コントリビュータの明確化

### ISSUE THREAD

**Issue by kotarot** [kotarot/wca-regulations-translations#53]
README および WCA の規則の翻訳ページ [＊] に記載されるコントリビュータは、今回の翻訳で力を貸してくれた石田さん、西さん、と私にしたいと考えています。
[＊] https://www.worldcubeassociation.org/regulations/translations/

その他の助言をしてくださった鈴木さん、および今回のベースとなった2012年の翻訳規則を作成した上野さん、桜井さん、佐藤さん、端村さん、長谷田さん、吉田さんは書いた文章が多く残っていることから acknowledgements として記しておきたいと思います。

**Comment by haseda** [comment]
賛成です！
acknowledgementsをどこまで遡って残すかは別の議論にしましょうか。

**Comment by kotarot** [comment]
そうですね。今回は上記の通りとします。
ご指摘のポイントは、次回の改訂から問題になってきそうなので、次回以降どうしていくか決めたいと考えています。

**Comment by kotarot** [comment]
定まった書き方は決められてなさそうなので割と自由に書き換えました。

**Comment by roudai** [comment]
鈴木さんは結局翻訳者の中に入れたんです？

**Comment by kotarot** [comment]
確かに上でコメントしたのと変えました。結局2015年版とそれ以外で分けました。

**Comment by kotarot** [comment]
あと、単に英文をなるべき書き換えたくなかったというのもあります。
下のやつ（in the past の位置をずらして、ついでに翻訳に参加した年も入れた）とどっちがいいですか？

## Contributors

The following people translated the latest regulations (Version: July 1, 2015):
- [Kotaro Terada (寺田晃太朗)](https://www.worldcubeassociation.org/results/p.php?i=2010TERA01)
- [Akihiro Ishida (石田朗大)](https://www.worldcubeassociation.org/results/p.php?i=2009ISHI01)
- [Kentaro Nishi (西賢太郎)](https://www.worldcubeassociation.org/results/p.php?i=2006NISH01)

## Acknowledgements

The following people helped with the translation in the past or by giving valuable feedback:
- [Yohei Suzuki (鈴木洋平)](https://www.worldcubeassociation.org/results/p.php?i=2006SUZU03) (contributed in 2015)
- [Shuto Ueno (上野柊斗)](https://www.worldcubeassociation.org/results/p.php?i=2008UENO01) (contributed in 2012)
- [Shun Sakurai (桜井駿)](https://www.worldcubeassociation.org/results/p.php?i=2010SAKU01) (contributed in 2012)
- [Shiori Sato (佐藤詩織)](https://www.worldcubeassociation.org/results/p.php?i=2013SATO01) (contributed in 2012)
- [Wataru Hashimura (端村航)](https://www.worldcubeassociation.org/results/p.php?i=2008HASH02) (contributed in 2012)
- [Takafumi Haseda (長谷田貴史)](https://www.worldcubeassociation.org/results/p.php?i=2006HASE01) (contributed in 2012)
- [Ayano Maria Yoshida (吉田彩乃)](https://www.worldcubeassociation.org/results/p.php?i=2009YOSH01) (contributed in 2012)

**Comment by roudai** [comment]
書き方としては、これでいいと思います。

https://www.worldcubeassociation.org/regulations/translations/
このページにある翻訳者の名前って、ここからとってくるんですかね？
もしそうなら、他の言語（韓国語）と合わせて括弧は半角でいいと思いますが、
関係ないなら全角のほうがいいかなと思います。

**Comment by kotarot** [comment]
そのページはここにマークダウンがあるので自動取得ではなくコピペで入力すると思いますが、このREADMEからコピーするか、WCAの個人ページからコピーするかは入力者の気分だと思います。プルリク送るときにも一応名前リストをコメントに書きたいと思っています。
https://github.com/cubing/worldcubeassociation.org/blob/master/regulations/pages/translations.md

このファイルの括弧ですが、英文の文書なので括弧は半角でいいと思います。

**Comment by roudai** [comment]
確かにそうですね、半角でOKです。

**Comment by kotarot** [comment]
反映しました。
タイトルだけは言語間で統一を持たせるために Contributors ではなくやっぱ Credits のままにしました。

**Comment by Yoheicube** [comment]
WCAにアップありがとうございます。

意見というか解釈部分等少しだけだったので、Acknowledgementsに記載していただけるのは少し気が引けますが。。。
また最後のほう、仕事が忙しくフォローできてなくて申し訳ありません。

JRCAのページにつきまして2014年となっていた部分を2015年に修正し、リンク等も修正いたしました。
それに伴い、Q＆Aも一部修正中です。

**Comment by kotarot** [comment]
@Yoheicube 
解釈を説明してくれたことで日本語作成に役立ちましたので謝辞に入れさせていただきました。

JRCAページの方の変更ありがとうございます。
今回の日本語はひとまず完成しましたので、今後これからの大会で活用してください。
今後の大会等で規則を使用して日本語の誤字や原文との解釈の違い等発見したときは、その都度お知らせください。できるだけすぐ反映するようにしたいと思います。
（メール等で完成報告をしようと思ったのですが、ここに書くことで留めさせてもらうことにします。）
