### ISSUE TITLE
注意書き「日本語版はあくまで参考、英語版が正式」の挿入の提案

### ISSUE THREAD

**Issue by kotarot** [kotarot/wca-regulations-translations#56]
[cubing/wca-regulations-translations](https://github.com/cubing/wca-regulations-translations) の master の README にも書いてありますが、

> Please note that this translation is not an official version (even though it is provided on the WCA website): it may be useful, but it does not come with any guarantees. If there is a difference between a translation and the (current official) English version, the English version must be used.

これとこれの日本語を付け加えたものを大会規則 (regulations.md) の冒頭らへんに書きたいと思うのですがどうですか。

**Comment by roudai** [comment]
どうせ日本人しか見ないから、原文は別にいらないんじゃ？

**Comment by kotarot** [comment]
「注意：日本語版の大会規則とガイドラインは WCA のウェブサイトで公開されていますが、公式のものではありません。WCA は翻訳内容を保証しないため参考程度にとどめてください。万一、日本語版と原文（英語版）に相違がある場合、原文の規則が適用されます。」

**Comment by kotarot** [comment]
> どうせ日本人しか見ないから、原文は別にいらないんじゃ？

いや、まあこの注意がただの訳注じゃなくて公式の告知であることを示したいので。無くてもいいけど。

**Comment by roudai** [comment]
まぁ、原文書いててもそこまで勘ぐる人は多分いないと思う。。。

**Comment by roudai** [comment]
公式ではありません→公式のものではありません

**Comment by kotarot** [comment]
そうですね。日本語だけにします。

**Comment by kotarot** [comment]
追加してみました。

**Comment by roudai** [comment]
いいと思います。
