### ISSUE TITLE
WCA大会規則・ガイドライン  ガイドラインへのリンク

### ISSUE THREAD

**Issue by roudai** [kotarot/wca-regulations-translations#57]
原文を見るとガイドラインへのリンクが貼らているので、日本語でもそうしたほうがいいかと。
`[WCA Guidelines](guidelines:top)`

**Comment by kotarot** [comment]
マークダウンのソースの方を見たらわかりやすいですが、既に張られています。
https://raw.githubusercontent.com/kotarot/wca-documents-translations/japanese-2015-07-01/wca-regulations.md

**Comment by roudai** [comment]
あぁすいません、ソース見たつもりだったけど古いほう見てました。
