### ISSUE TITLE
H1d) 「ペナルティー」を「ペナルティ」に修正

### ISSUE THREAD

**Issue by nikken7101** [kotarot/wca-regulations-translations#6]
# 修正箇所

H1d
# 修正案

`H1d) 試技を行ったパズルに対する +2 秒ペナルティは累積される。`
# 修正理由

`ペナルティー`という表現は他にないが、`ペナルティ`という表現は19箇所あるので、統一すべき

**Comment by kotarot** [comment]
これは明らかに統一すべきです。統一しました。
