### ISSUE TITLE
B2e) 「スタックタイマー」を「スタックマットタイマー」に修正

### ISSUE THREAD

**Issue by nikken7101** [kotarot/wca-regulations-translations#8]
# 修正箇所

B2e
# 修正案

`B2e) スタックマットタイマーに加えてストップウォッチを計測に使用する場合、ジャッジは試技が開始されたらすぐにストップウォッチをスタートさせる。`
# 理由

`スタックタイマー`という単語はここでしか使われていない。18箇所で使われている`スタックマットタイマー`が適切だと思われる。

**Comment by kotarot** [comment]
明らかに修正すべき点です。直しました。
